version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic

formatters:
  enable:
    - gofmt

linters-settings:
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - badLock
      - badRegexp
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - nilValReturn
      - sloppyLen
      - truncateCmp
      - unnecessaryDefer
      - weakCond

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
